// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eKvarovi.Api.Data;

#nullable disable

namespace eKvarovi.Api.Migrations
{
    [DbContext(typeof(EKvaroviDbContext))]
    partial class EKvaroviDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("eKvarovi.Shared.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Korisnik",
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Administrator",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Upravitelj",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Izvršitelj",
                            Name = "Technician"
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Prijavitelj",
                            Name = "Reporter"
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("TechnicianId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppUserId", "AppRoleId");

                    b.HasIndex("AppRoleId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachmentPurpose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaultReportId");

                    b.HasIndex("InterventionId");

                    b.ToTable("FaultMedia");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FaultPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nizak"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Srednji"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Visok"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kritičan"
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FaultPriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaultStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FaultTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReporterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaultPriorityId");

                    b.HasIndex("FaultStatusId");

                    b.HasIndex("FaultTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReporterId");

                    b.ToTable("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FaultStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zaprimljeno"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pregledano"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dodijeljeno"
                        },
                        new
                        {
                            Id = 4,
                            Name = "U radu"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Riješeno"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zatvoreno"
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FaultTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektrika"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Voda"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grijanje"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mreža"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Građevinski radovi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ostalo"
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterventionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkNote")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionStatusId");

                    b.HasIndex("WorkAssignmentId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.InterventionMaterial", b =>
                {
                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("InterventionId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("InterventionMaterials");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.InterventionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InterventionStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Planirana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "U tijeku"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Završena"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Neuspješna"
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Upravna zgrada"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Škola"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zdravstvena ustanova"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Skladište"
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialUnitId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.MaterialUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaterialUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Komad"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Metar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Litra"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Paket"
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.WorkAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FaultReportId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = 1");

                    b.HasIndex("TechnicianId");

                    b.ToTable("WorkAssignments");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUser", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eKvarovi.Shared.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUserRole", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Employee", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultMedia", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.FaultReport", "FaultReport")
                        .WithMany("Media")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.Intervention", "Intervention")
                        .WithMany("Media")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FaultReport");

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultReport", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.FaultPriority", "FaultPriority")
                        .WithMany("FaultReports")
                        .HasForeignKey("FaultPriorityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eKvarovi.Shared.Models.FaultStatus", "FaultStatus")
                        .WithMany("FaultReports")
                        .HasForeignKey("FaultStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.FaultType", "FaultType")
                        .WithMany("FaultReports")
                        .HasForeignKey("FaultTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eKvarovi.Shared.Models.Location", "Location")
                        .WithMany("FaultReports")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.Employee", "Reporter")
                        .WithMany("ReportedFaults")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FaultPriority");

                    b.Navigation("FaultStatus");

                    b.Navigation("FaultType");

                    b.Navigation("Location");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Intervention", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.InterventionStatus", "InterventionStatus")
                        .WithMany("Interventions")
                        .HasForeignKey("InterventionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.WorkAssignment", "WorkAssignment")
                        .WithMany("Interventions")
                        .HasForeignKey("WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterventionStatus");

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.InterventionMaterial", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.Intervention", "Intervention")
                        .WithMany("Materials")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.Material", "Material")
                        .WithMany("Interventions")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Location", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Material", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.MaterialUnit", "MaterialUnit")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialUnit");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.WorkAssignment", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.FaultReport", "FaultReport")
                        .WithMany("Assignments")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.Technician", "Technician")
                        .WithMany("WorkAssignments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FaultReport");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Employee", b =>
                {
                    b.Navigation("ReportedFaults");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultPriority", b =>
                {
                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultReport", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultStatus", b =>
                {
                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultType", b =>
                {
                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Intervention", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.InterventionStatus", b =>
                {
                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Material", b =>
                {
                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.MaterialUnit", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Technician", b =>
                {
                    b.Navigation("WorkAssignments");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.WorkAssignment", b =>
                {
                    b.Navigation("Interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
